version: 2

project_name: t

archives:
- files:
  - LICENSE.md
  - README.md
  name_template: >-
    t_{{ .Version }}_
    {{- title .Os }}_
    {{- if eq .Arch "amd64" }}x86_64
    {{- else }}{{ .Arch }}{{ end }}
    {{- with .Arm }}v{{ . }}{{ end }}
  wrap_in_directory: true

before:
  hooks:
  - go mod tidy

builds:
- env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - linux
  ldflags:
  - -s -w -X github.com/unfunco/t/internal/version.SemanticVersion={{ .Version }}

checksum:
  name_template: checksums.txt

release:
  draft: false
  github:
    owner: unfunco
    name: t
  prerelease: auto
